### ISSUE TITLE
Roadmap to production-ready mega-thread

### ISSUE THREAD

**Issue by BusinessDuck** [alpacahq/typescript-sdk#1]
Hi! I see that the project is almost ready. Let me express my gratitude for your contribution to the algo trading community. I'm really looking forward, like many others, to the latest version of the typescript API for alpaca. Thank you for creating this project. 

I would like to know if there will be crypto support out of the box in the first release? This is very important because it is difficult to test real positions because we immediately run into daily trading limits, and there are no such limits on crypto assets. I'm really looking forward to the appearance of crypto assets in the API so that I can work and study the behavior of transactions in the real market.

**Comment by BusinessDuck** [comment]
By the way, if you have beta, let me try i'll test it and send you a report asap. And may be fix in MR

**Comment by 117** [comment]
Hey, thanks for the kind words! The library will be published this week with **_full coverage_** of the trading and market data APIs, including crypto. Just need to clean up the types and set up the build process. The core logic is all done. Will tag you first thing 😉 when its out.

**Comment by 117** [comment]
Ok, I have a deployment action setup, it is now being published to NPM. I have tested a good amount of the trading API endpoints, market data next. Types are a bit brutal to cleanup but i'm getting there. Feel free to install and test at will while I develop further.

**Comment by 117** [comment]
Also the WebSocket is functional but the types are .. in progress to say the least.

**Comment by BusinessDuck** [comment]
Good news, i'll start with btc now, because stocks are out of market time. I Will send to this thread everything what i can find. Also after migration (from master chief's library) i can make a PR

**Comment by BusinessDuck** [comment]
Doc:
> By default, the client will make requests to the paper trading environment (https://paper-api.alpaca.markets). This is a safety measure to prevent accidental trades.

Real one:
Parameter `baseUrl` is required and have no default value
<img width="891" alt="image" src="https://github.com/alpacahq/typescript-sdk/assets/10143411/0b0eee82-8254-416f-9be3-3ddc008cc6f9">

Expected: 
- [ ] Default value is paper for baseUrl, parameter is optional 
- [ ] Clarify in documentation the difference between streams and REST (that mean anything will works through the socket? Will socket used also for orders (open/close)?

**Comment by BusinessDuck** [comment]
After the first look at the client i guess i need two different clients with same credentials: One for the market access and another for the data stream, is that right?


- [ ] Add an example for market & stream

**Comment by BusinessDuck** [comment]
How i do change the source for baseUrl? take a look an example [here](https://github.com/alpacahq/alpaca-ts?tab=readme-ov-file#creating-a-new-stream) and its described [here](https://docs.alpaca.markets/docs/stock-pricing-api#trading-api) 

<img width="729" alt="image" src="https://github.com/alpacahq/typescript-sdk/assets/10143411/4450712a-df93-476b-813e-020e78b9d63c">

- [ ] Add source parameter to client factory `createClient`

**Comment by BusinessDuck** [comment]
<img width="522" alt="image" src="https://github.com/alpacahq/typescript-sdk/assets/10143411/3fcbcfbd-9765-4144-854d-09cf1dc2f9c1">

- [ ] Add `once` event subscription (default for `EventEmiiters` today) its a bit friendly.


Also regarding with connection. Can you please clarify how it works now, i need answers to the following questions:
 - All connection keep alive logic is under the hood and i don't need to do anything with handle connections loses on my side?
 - Will subscriptions are restored after reconnect?

**Comment by BusinessDuck** [comment]
I need an example with this call:

```typescript
const res = await this.api.v2.assets.get({ symbol_or_asset_id: ticker }); // looks wrong
const res = await this.api.v2.assets[':symbol_or_asset_id'].get({ symbol_or_asset_id: ticker }); // looks right but not clear
```

**Comment by BusinessDuck** [comment]
Also i need example  with market data subscribtions channels - How to subscribe to quotes and bars and handle it?

<img width="623" alt="image" src="https://github.com/alpacahq/typescript-sdk/assets/10143411/2fdb9335-1570-4421-87ab-d3129bbc14e3">

Also i dont see the `Bar` or `RawBar` types or something similar for incoming data in npm module exports, where it is?

**Comment by BusinessDuck** [comment]
Is that right? May be `unlisten` here? Same for other subscribe removers in market and data

https://github.com/alpacahq/typescript-sdk/blob/ca5ab8f5885474c2c5183c89061bf87e9c12ba6f/src/api/trade.ts#L850

**Comment by 117** [comment]
A default `baseURL` would mean that you must know in advance whether to provide either paper or live keys. I wanted to go for a more explicit approach, maybe that's worth re-thinking 🤷🏻 . 

I'll add source, good catch. WebSocket is _very_ unfinished right now, I will do that tomorrow before I cleanup/add the types for the market data endpoints.

Now as far as the below is concerned..

```ts
const res = await this.api.v2.assets.get({ symbol_or_asset_id: ticker }); // looks wrong
const res = await this.api.v2.assets[':symbol_or_asset_id'].get({ symbol_or_asset_id: ticker }); // looks right but not clear
```

The idea here was to mimic the path of the endpoint. I don't know what to do about those types of endpoints.. if I break convention with something like a `getById` that would make it more clear I suppose. What do you think?

I could also just say screw it and go back to `.getAccount`, `.getAsset`, `.getOrder` 😕 lol

**Comment by 117** [comment]
> <img alt="image" width="522" src="https://private-user-images.githubusercontent.com/10143411/318186744-3fcbcfbd-9765-4144-854d-09cf1dc2f9c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTU5NDYsIm5iZiI6MTcxMTc5NTY0NiwicGF0aCI6Ii8xMDE0MzQxMS8zMTgxODY3NDQtM2ZjYmNmYmQtOTc2NS00MTQ0LTg1NGQtMDljZjFkYzJmOWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDEwNDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNWRlN2IzMWMwNmFkMDYxM2RhN2ZjZjJkOTBiMTExYjAxNmVhNjYzOGYzZDRmY2VkYjZmNDM2NWQ2Mjk5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CDjCPp1a7FROJVTeeVAefaC0RppojyQ3gI2UgBG_-qM">
> * [ ]  Add `once` event subscription (default for `EventEmiiters` today) its a bit friendly.
> 
> Also regarding with connection. Can you please clarify how it works now, i need answers to the following questions:
> 
> * All connection keep alive logic is under the hood and i don't need to do anything with handle connections loses on my side?
> * Will subscriptions are restored after reconnect?

Yes I intend to add reconnect options to the client params, `maxRetries`, `backOff` etc.  I will also add a `.reconnect()` in the context if you wish to do that manually.

**Comment by 117** [comment]
Honestly, going back to the camel case getters would make my life a lot easier as far as the types are concerned. Compiling a list of all this, keep it coming 😄.

**Comment by BusinessDuck** [comment]
> The idea here was to mimic the path of the endpoint. I don't know what to do about those types of endpoints.. if I break convention with something like a getById that would make it more clear I suppose. What do you think?
> I could also just say screw it and go back to .getAccount, .getAsset, .getOrder 😕 lol


I like an idea to use `v2` as versioning parameter that's super good for default REST versioning and back compatibility. So and relates to call method style i think its default to have a different methods like `getAssets` and etc many other financial SDK also on that way. When we are in default that mean its easy to migrate to that SDK from another one.

**Comment by BusinessDuck** [comment]
>Yes I intend to add reconnect options to the client params, maxRetries, backOff etc. I will also add a .reconnect() in the context if you wish to do that manually.

I wont do :) I want to have a stable access to market and data, and that is everything what i really need :)

**Comment by 117** [comment]
> >Yes I intend to add reconnect options to the client params, maxRetries, backOff etc. I will also add a .reconnect() in the context if you wish to do that manually.
> 
> 
> 
> I wont do :) I want to have a stable access to market and data, and that is everything what i really need :) 

will update this all tomorrow 👍, late here at the moment.

an unstable websocket is very annoying ill make sure it stays connected within the client

**Comment by 117** [comment]
Ok just powered through refactoring all of the trading api methods https://github.com/alpacahq/typescript-sdk/tree/main?tab=readme-ov-file#methods. How do we feel about that? I like it, maybe all of the crypto ones need "crypto" in the method names though.

Build will be failing, I have to refactor the `createClient` and market data next. I am going to make the `baseURL` auto-detect based on either paper or live keys, it will use the right URL for the given method you call.

You can see the re-written code [here](https://github.com/alpacahq/typescript-sdk/blob/main/src/api/trade.ts).

**Comment by 117** [comment]
Taking a break today, will get the build working and trading api methods consumable so you can test it a bit later.

**Comment by 117** [comment]
### Trading API

```
---- base ----

getAccount ✅
createOrder ✅
getOrder ✅
getOrders ✅
replaceOrder ✅
cancelOrders ✅
cancelOrder ✅
getPosition ✅
getPositions ✅
closePosition ✅
closePositions ✅
exerciseOption ✅
getCalendar ✅
getClock ✅
getAsset ✅
getAssets ✅
getWatchlist ✅
getWatchlists ✅
createWatchlist ✅
updateWatchlist ✅
deleteWatchlist ✅
getPortfolioHistory ✅
getConfigurations ✅
updateConfigurations ✅
getActivity ✅
getActivities ✅

---- options ----

getOptionsContract ✅
getOptionsContracts ✅
getStocksCorporateAction ✅
getStocksCorporateActions ✅

---- crypto ----

getCryptoWallet ✅
getCryptoWallets ✅
getCryptoFeeEstimate ✅
getCryptoTransfer ✅
getCryptoTransfers ✅
createCryptoTransfer ✅
getCryptoWhitelistedAddress ✅
getCryptoWhitelistedAddresses ✅
requestCryptoWhitelistedAddress ✅
removeCryptoWhitelistedAddress ✅
```
### Market Data API

```
---- all ----

getNews ✅
getStocksLogo ✅


---- stocks ----

getStocksCorporateActions ✅
getStocksMostActives ✅
getStocksMarketMovers ✅
getStocksQuotes ✅
getStocksQuotesLatest ✅
getStocksBars ✅
getStocksBarsLatest ✅
getStocksSnapshots ✅
getStocksAuctions ✅
getStocksConditions ✅
getStocksExchangeCodes ✅
getStocksTrades ✅
getStocksTradesLatest ✅

---- forex ----

getForexRates ✅
getForexRatesLatest ✅

---- options ----

getOptionsBars ✅
getOptionsExchanges ✅
getOptionsSnapshots ✅
getOptionsTrades ✅
getOptionsTradesLatest ✅

---- crypto ----

getCryptoBars ✅
getCryptoBarsLatest ✅
getCryptoQuotes ✅
getCryptoQuotesLatest ✅
getCryptoSnapshots ✅
getCryptoTrades ✅
getCryptoTradesLatest ✅
getCryptoOrderbooksLatest ✅
```

Working on websocket now.

**Comment by BusinessDuck** [comment]
Can you create a beta release? I will try to use 

Use the _npm publish --tag beta_

**Comment by 117** [comment]
Check latest, added method examples to README too. https://github.com/alpacahq/typescript-sdk?tab=readme-ov-file#methods

**Comment by 117** [comment]
Doing WebSocket now.

**Comment by 117** [comment]
So far https://github.com/alpacahq/typescript-sdk/blob/main/factory/createStream.ts, types and auxiliary functions next.

**Comment by BusinessDuck** [comment]
`import { createClient, Client } from '@alpacahq/typescript-sdk';` client is not exported from sdk, that needs for usage like:

```typescript
...
protected api: Client;
...

this.api = createClient({ key, secret });
```

Hacky way working now:

```typescript
...
protected api: ReturnType<typeof createClient>;
...
```

**Comment by BusinessDuck** [comment]
Typings wrong in `0.0.24-preview`

<img width="854" alt="image" src="https://github.com/alpacahq/typescript-sdk/assets/10143411/42b9948b-00d0-42de-b81b-fc5a38216c54">

Not same with described [here](https://github.com/alpacahq/typescript-sdk?tab=readme-ov-file#getasset)

**Comment by 117** [comment]
> Typings wrong in `0.0.24-preview`
> <img alt="image" width="854" src="https://private-user-images.githubusercontent.com/10143411/323317477-42b9948b-00d0-42de-b81b-fc5a38216c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzY5MTUsIm5iZiI6MTcxNTM3NjYxNSwicGF0aCI6Ii8xMDE0MzQxMS8zMjMzMTc0NzctNDJiOTk0OGItMDBkMC00MmRlLWI4MWItZmM1YTM4MjE2YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIxMzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZGMwMDYzNTljYzUyNDA0MGYzMWFhY2UzOGM3NDAwZGM4NWExODUwNGI0MTU1MmNkMzA1NjA0NTY4ZjlhZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uQeUIsq65PziZZW-ZgR15ANyist408LMj-822k9PJ4c">
> 
> Not same with described [here](https://github.com/alpacahq/typescript-sdk?tab=readme-ov-file#getasset)

Try latest, replit [here](https://replit.com/@11714/TwinFrozenPrinter).

**Comment by BusinessDuck** [comment]
missed "types" field in package json
<img width="783" alt="image" src="https://github.com/alpacahq/typescript-sdk/assets/10143411/f24f56b9-e0ec-4e70-8fa7-ba6922830700">


```
node -v
v18.19.0

npm -v
10.2.3
```

**Comment by 117** [comment]
> missed "types" field in package json <img alt="image" width="783" src="https://private-user-images.githubusercontent.com/10143411/331853788-f24f56b9-e0ec-4e70-8fa7-ba6922830700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTY2NjAsIm5iZiI6MTcxNzk1NjM2MCwicGF0aCI6Ii8xMDE0MzQxMS8zMzE4NTM3ODgtZjI0ZjU2YjktZTBlYy00ZTcwLThmYTctYmE2OTIyODMwNzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE4MDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMzVhMzE4NGEzNmRjMWRiMWM1MmViZDhiOGM1ODRlMjk4OTk4NjM4MTdkNTMyZDFjYjMwNjNlYzFmM2ExMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9XgZUSdkE9nzjwFDuYcIiU6pYy9CJnSzfODuaxm_z-g">
> 
> ```
> node -v
> v18.19.0
> 
> npm -v
> 10.2.3
> ```

added

**Comment by vicary** [comment]
I want to try WebSockets with `createStream`, but as of `0.0.31-preview` the file does not exist in the NPM bundle. How should I import it?

**Comment by tvdaredevil** [comment]
FYI, the corporate actions api has been deprecated but the lib still uses the deprecated way:

![Image](https://github.com/user-attachments/assets/261a6b15-cf5c-4d67-8ae9-efdc327c7319)

**Comment by erwan-joly** [comment]
How do we contribute to this library ? 
it seems like there are issues with pr that are not getting merged so what should we do to get those merged ? https://github.com/alpacahq/typescript-sdk/issues/13

**Comment by vicary** [comment]
@erwan-joly Quoting the response to [my similar question](https://discord.com/channels/878427978223194123/951500849077698560/1314479564293931048) in the Discord Q&A channel:

> I think you're talking about the one made by a spartan 116 or something?
> Turns out that was one of Alpacas front-end engineers who's no longer with them
> I doubt he's maintaining it any more
> And Alpaca doesn't officially support it either, never did, but internally they "appreciated" his work on it
> I'm sure you can make a wrapper for their official SDK
> 
> vs﹒HawkAlpha 08/12/2024, 00:59

Unless they explicitly say that they are picking this up, I think the best chance anything would happen is that they add `@types` to their existing js sdk.

**Comment by sachyco** [comment]
Hi everyone - some sad news: from today, we're officially archiving this project. It was indeed championed by one of our frontend engineers who is no longer with the company. We have no plans to maintain or improve this SDK.

Please see [alpaca-trade-api-js](https://github.com/alpacahq/alpaca-trade-api-js/) for our official JS/TS/Node SDK.
